### ISSUE TITLE
BLOG: Povolit komentáře?

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/kovork#13]

**Comment by smutna** [comment]
Může být. Vidíš tam nějaké riziko? Spamoví roboti?

**Comment by janfluksa** [comment]
Ne, to se dá zmírnit. Spíš jde o to, že to bude muset někdo moderovat. 

Pokud se nechceš starat o další portál nebudeme komentáře povolovat. V případě, že používáte nějaký centralizovaný systém, jako je třeba BrandEmbassy, tak WP můžeme integrovat. 

Také můžeme ukol uzavřít a nechat si ho na případ, až bude potřeba komentáře u příspěvků pustit. Osobně dávám přednost diskusím na sociálních sítích, kam patří :)

**Comment by smutna** [comment]
Komentáře ne.
