### ISSUE TITLE
Dopllnit výpis z twitteru do patičky

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/kovork#2]

**Comment by janfluksa** [comment]
Budu potřebovat Twitter ID z dvelopers.twitter.com

**Comment by smutna** [comment]
Ahoj, začala jse vytvářet widget přímo někde v nastavení. Jaký kód chceš vygenerovat? Dark version nebo light version? Rovněž automaticky se to nastavuj na výšku 600 px, mám tu výšku nějak upravit? Děkuji. K.
![twitter widget dark](https://cloud.githubusercontent.com/assets/11783695/6981107/ce291572-d9fc-11e4-97e6-0f7ba8d44b0d.PNG)
![twitter widget light](https://cloud.githubusercontent.com/assets/11783695/6981108/ce291fc2-d9fc-11e4-90d7-cb0f7e98dbef.PNG)

**Comment by janfluksa** [comment]
Když dáš to tlačítko *Create*, tak se ti tam ten nový widget objeví. Pak stačí zkopírovat **URL adresu** a poslat mi ji emailem. Ten kód je obsažen v adrese. Honza

**Comment by smutna** [comment]
https://twitter.com/settings/widgets/586143468210257921/edit?focus_textarea=1&notice=WIDGET_CREATED

<a class="twitter-timeline" href="https://twitter.com/inkubatorvsb" data-widget-id="586143468210257921">Tweets by @inkubatorvsb</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

**Comment by janfluksa** [comment]
Myslím, že je to hezké :)

![image](https://cloud.githubusercontent.com/assets/3913922/7121275/b58043a0-e213-11e4-91a6-7430c9e59def.png)
