### ISSUE TITLE
KAM 4: Blog - poslední příspěvky / servis?

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/kovork#23]
![5 kovork](https://cloud.githubusercontent.com/assets/3913922/6945049/65b486e0-d897-11e4-9e6c-7526bc7f3ada.PNG)

**Comment by janfluksa** [comment]
Nadpis přejmenován
![image](https://cloud.githubusercontent.com/assets/3913922/6945621/4e49603a-d89b-11e4-9677-690c132c0dbb.png)

**Comment by janfluksa** [comment]
Servisní zprávy zatím nemám vyřešené ale jedná se o úkol #5

**Comment by janfluksa** [comment]
Archiv příspěvků existuje na stránce http://apache.abwebsites.cz/dev.kovork.cz/kovork-blog/
Doplním pod výpis odkaz

**Comment by janfluksa** [comment]
![image](https://cloud.githubusercontent.com/assets/3913922/6945709/fd8fc34a-d89b-11e4-88d4-ec7aa3a24790.png)

**Comment by smutna** [comment]
Teď si nejsem jistá, je zde ode mě potřeba nějaká akce?

**Comment by janfluksa** [comment]
Stačí jen potvrdit, že je to tak v pořádku. Díky, H
