### ISSUE TITLE
KAM 7: Ceny

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/kovork#24]
![7 kovork](https://cloud.githubusercontent.com/assets/3913922/6945056/751d60ca-d897-11e4-87b1-e190451af9eb.PNG)

**Comment by janfluksa** [comment]
Program kancelář je pryč

**Comment by janfluksa** [comment]
Navrhuji **Ceník služeb**, když už je to v menu.
Prosím o potvrzení. Díky, Honza

**Comment by smutna** [comment]
Za mě o.k. ješte zjistím s Viktorem a definitivně potvrdím.

**Comment by smutna** [comment]
Viktor souhlasí, Ceník služeb.

**Comment by janfluksa** [comment]
Přejmenováno

![image](https://cloud.githubusercontent.com/assets/3913922/7115495/74000e3a-e1e9-11e4-9364-c00b116d4bcd.png)
