### ISSUE TITLE
Zvětšit písmo v MENU

### ISSUE THREAD

**Issue by smutna** [janfluksa/kovork#31]

**Comment by janfluksa** [comment]
Ahoj kamčo,

fonty jsem změnil z velikosti 13px na 15px. Je to dostačující?

Díky, Honza

**Comment by janfluksa** [comment]
16px

**Comment by janfluksa** [comment]
Písmo jsem zvětšil na 16px

![image](https://cloud.githubusercontent.com/assets/3913922/7453849/cc336c02-f26d-11e4-8648-35d5b6e98b10.png)
