### ISSUE TITLE
Může být úvodní slider bez Paralax efektu?

### ISSUE THREAD

**Issue by janfluksa** [janfluksa/kovork#9]

**Comment by smutna** [comment]
Pokud se jedná o ten pohyblivý efekt (musela jsem s vygoglit, co to paralax effect je :-) tak asi ano. Není nezbytně nutné jej tam mít, pokud to dělá neplechu.

**Comment by janfluksa** [comment]
No, šel by tam, jen by to nebyl slider. Zatím počítám stím, že slider využijeme jako promo. Doufám, že najdeme ještě jiný způsob. 

Otázka je: Nastane chvíle, že by tam nebylo žádné promo?

**Comment by smutna** [comment]
LayerSlider WP

**Comment by janfluksa** [comment]
Domluveno :)
